[versions]
hivemq-mqttClient = "1.3.1"
jetbrains-annotations = "24.0.1"
junit-jupiter = "5.9.3"
logback = "1.4.7"
mockito = "4.11.0"
testcontainers = "1.19.7"
log4j = "2.23.1"
mssql-jdbc = "12.6.1.jre11"

[libraries]
hivemq-mqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqttClient" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
testcontainers-hivemq = { module = "org.testcontainers:hivemq", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
log4j = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j"}
mssql-jdbc = {module = "com.microsoft.sqlserver:mssql-jdbc", version.ref = "mssql-jdbc"}

[plugins]
hivemq-extension = { id = "com.hivemq.extension", version = "3.0.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }